schema: ae.canonical.meta.v1
concept: ecsly
version: 1
title: ecsly
license:
  spdx: CC-BY-4.0
  url: "https://creativecommons.org/licenses/by/4.0/"
authors: []
sources: []
provenance:
  authored: scaffolded
  authored_at: "2026-08-24T07:48:33.118276Z"
